# Generated by Django 3.0.5 on 2021-05-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_alter_doctor_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='MednTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40)),
                ('assignedDoctorName', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('medicine', models.CharField(max_length=100, null=True)),
                ('medicineCost', models.PositiveIntegerField()),
                ('test', models.CharField(max_length=100, null=True)),
                ('testCost', models.PositiveIntegerField()),
                ('doctorFee', models.PositiveIntegerField()),
                ('OtherCharge', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='medicine',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
