# Generated by Django 3.0.5 on 2021-06-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_remove_patient_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medntest',
            name='OtherCharge',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medntest',
            name='doctorFee',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medntest',
            name='medicineCost',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medntest',
            name='testCost',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medntest',
            name='total',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='OtherCharge',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='admitDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='daySpent',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='doctorFee',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='medicineCost',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='releaseDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='roomCharge',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='total',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
