# Generated by Django 3.0.5 on 2021-06-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_auto_20210601_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='medntest',
            name='conclusion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medntest',
            name='result',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
